const blocColors = {
  APEC: "#f5f5f5",
  ASEAN: "#ff9500",
  CARICOM: "#a318c4",
  CEDEAO: "#f4511e",
  CEI: "#1836d6",
  MCCA: "#ff2d87",
  Mercosul: "#159f2e",
  PactoAndino: "#ffd400",
  SADC: "#a89400",
  USMCA: "#f5232f",
  UniaoEuropeia: "#5fd06f",
  default: "#dcdcdc",
};

const countryToBloc = {
  Argentina: "Mercosul",
  Brazil: "Mercosul",
  Paraguay: "Mercosul",
  Uruguay: "Mercosul",

  Austria: "UniaoEuropeia",
  Belgium: "UniaoEuropeia",
  Bulgaria: "UniaoEuropeia",
  Croatia: "UniaoEuropeia",
  Cyprus: "UniaoEuropeia",
  Czechia: "UniaoEuropeia",
  Denmark: "UniaoEuropeia",
  Estonia: "UniaoEuropeia",
  Finland: "UniaoEuropeia",
  France: "UniaoEuropeia",
  Germany: "UniaoEuropeia",
  Greece: "UniaoEuropeia",
  Hungary: "UniaoEuropeia",
  Ireland: "UniaoEuropeia",
  Italy: "UniaoEuropeia",
  Latvia: "UniaoEuropeia",
  Lithuania: "UniaoEuropeia",
  Luxembourg: "UniaoEuropeia",
  Malta: "UniaoEuropeia",
  Netherlands: "UniaoEuropeia",
  Poland: "UniaoEuropeia",
  Portugal: "UniaoEuropeia",
  Romania: "UniaoEuropeia",
  Slovakia: "UniaoEuropeia",
  Slovenia: "UniaoEuropeia",
  Spain: "UniaoEuropeia",
  Sweden: "UniaoEuropeia",

  "United States of America": "USMCA",
  Canada: "USMCA",
  Mexico: "USMCA",

  Brunei: "ASEAN",
  Cambodia: "ASEAN",
  Indonesia: "ASEAN",
  Laos: "ASEAN",
  Malaysia: "ASEAN",
  Myanmar: "ASEAN",
  Philippines: "ASEAN",
  Singapore: "ASEAN",
  Thailand: "ASEAN",
  Vietnam: "ASEAN",

  Bolivia: "PactoAndino",
  Colombia: "PactoAndino",
  Ecuador: "PactoAndino",
  Peru: "PactoAndino",

  Armenia: "CEI",
  Azerbaijan: "CEI",
  Belarus: "CEI",
  Kazakhstan: "CEI",
  Kyrgyzstan: "CEI",
  Moldova: "CEI",
  Russia: "CEI",
  Tajikistan: "CEI",
  Turkmenistan: "CEI",
  Uzbekistan: "CEI",

  "Costa Rica": "MCCA",
  "El Salvador": "MCCA",
  Guatemala: "MCCA",
  Honduras: "MCCA",
  Nicaragua: "MCCA",

  Bahamas: "CARICOM",
  Barbados: "CARICOM",
  Belize: "CARICOM",
  Guyana: "CARICOM",
  Haiti: "CARICOM",
  Jamaica: "CARICOM",
  Suriname: "CARICOM",
  "Trinidad and Tobago": "CARICOM",

  Benin: "CEDEAO",
  "Burkina Faso": "CEDEAO",
  "Cabo Verde": "CEDEAO",
  "Cape Verde": "CEDEAO",
  "Ivory Coast": "CEDEAO",
  "Côte d'Ivoire": "CEDEAO",
  Gambia: "CEDEAO",
  Ghana: "CEDEAO",
  Guinea: "CEDEAO",
  "Guinea-Bissau": "CEDEAO",
  Liberia: "CEDEAO",
  Mali: "CEDEAO",
  Niger: "CEDEAO",
  Nigeria: "CEDEAO",
  Senegal: "CEDEAO",
  "Sierra Leone": "CEDEAO",
  Togo: "CEDEAO",

  Angola: "SADC",
  Botswana: "SADC",
  "Dem. Rep. Congo": "SADC",
  "Democratic Republic of the Congo": "SADC",
  Eswatini: "SADC",
  Swaziland: "SADC",
  Lesotho: "SADC",
  Madagascar: "SADC",
  Malawi: "SADC",
  Mauritius: "SADC",
  Mozambique: "SADC",
  Namibia: "SADC",
  "South Africa": "SADC",
  Tanzania: "SADC",
  Zambia: "SADC",
  Zimbabwe: "SADC",
};

const apecMembers = new Set([
  "Australia",
  "Brunei",
  "Canada",
  "Chile",
  "China",
  "Indonesia",
  "Japan",
  "South Korea",
  "Malaysia",
  "Mexico",
  "New Zealand",
  "Papua New Guinea",
  "Peru",
  "Philippines",
  "Russia",
  "Singapore",
  "Taiwan",
  "Thailand",
  "United States of America",
  "Vietnam",
]);

const blocStats = {
  APEC: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  ASEAN: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  CARICOM: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  CEDEAO: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  CEI: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  MCCA: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  Mercosul: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  PactoAndino: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  SADC: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  USMCA: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
  UniaoEuropeia: { valorExportado: null, valorImportado: null, paisMaisExportador: null, paisMaisImportador: null },
};

const blocLabels = {
  APEC: "APEC (Cooperação Econômica Ásia-Pacífico)",
  ASEAN: "ASEAN (Associação de Nações do Sudeste Asiático)",
  CARICOM: "CARICOM (Comunidade do Caribe)",
  CEDEAO: "CEDEAO (Comunidade Econômica dos Estados da África Ocidental)",
  CEI: "CEI (Comunidade dos Estados Independentes)",
  MCCA: "MCCA (Mercado Comum Centro-Americano)",
  Mercosul: "Mercosul (Mercado Comum do Sul)",
  PactoAndino: "Pacto Andino (Comunidade Andina)",
  SADC: "SADC (Comunidade para o Desenvolvimento da África Austral)",
  USMCA: "USMCA (Acordo Estados Unidos-México-Canadá)",
  UniaoEuropeia: "União Europeia",
  default: "Outros",
};

export { blocColors, countryToBloc, apecMembers, blocLabels, blocStats };
