const countryNamesPt = {
  Afghanistan: "Afeganistão",
  Albania: "Albânia",
  Algeria: "Argélia",
  Angola: "Angola",
  Argentina: "Argentina",
  Armenia: "Armênia",
  Australia: "Austrália",
  Austria: "Áustria",
  Azerbaijan: "Azerbaijão",
  Bahrain: "Barein",
  Bangladesh: "Bangladesh",
  Belarus: "Bielorrússia",
  Belgium: "Bélgica",
  Bolivia: "Bolívia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  Botswana: "Botsuana",
  Brazil: "Brasil",
  Brunei: "Brunei",
  Bulgaria: "Bulgária",
  Cambodia: "Camboja",
  Cameroon: "Camarões",
  Canada: "Canadá",
  Chad: "Chade",
  Chile: "Chile",
  China: "China",
  Colombia: "Colômbia",
  Croatia: "Croácia",
  Cuba: "Cuba",
  Cyprus: "Chipre",
  Czechia: "Tchéquia",
  Denmark: "Dinamarca",
  "Dominican Republic": "República Dominicana",
  Ecuador: "Equador",
  Egypt: "Egito",
  "El Salvador": "El Salvador",
  Estonia: "Estônia",
  Ethiopia: "Etiópia",
  Finland: "Finlândia",
  France: "França",
  Georgia: "Geórgia",
  Germany: "Alemanha",
  Ghana: "Gana",
  Greece: "Grécia",
  Guatemala: "Guatemala",
  Honduras: "Honduras",
  Hungary: "Hungria",
  Iceland: "Islândia",
  India: "Índia",
  Indonesia: "Indonésia",
  Iran: "Irã",
  Iraq: "Iraque",
  Ireland: "Irlanda",
  Israel: "Israel",
  Italy: "Itália",
  Jamaica: "Jamaica",
  Japan: "Japão",
  Jordan: "Jordânia",
  Kazakhstan: "Cazaquistão",
  Kenya: "Quênia",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Quirguistão",
  Laos: "Laos",
  Latvia: "Letônia",
  Lebanon: "Líbano",
  Libya: "Líbia",
  Lithuania: "Lituânia",
  Luxembourg: "Luxemburgo",
  Malaysia: "Malásia",
  Mali: "Mali",
  Malta: "Malta",
  Mexico: "México",
  Mongolia: "Mongólia",
  Morocco: "Marrocos",
  Myanmar: "Mianmar",
  Namibia: "Namíbia",
  Nepal: "Nepal",
  Netherlands: "Países Baixos",
  "New Zealand": "Nova Zelândia",
  Nicaragua: "Nicarágua",
  Nigeria: "Nigéria",
  "North Korea": "Coreia do Norte",
  Norway: "Noruega",
  Oman: "Omã",
  Pakistan: "Paquistão",
  Panama: "Panamá",
  "Papua New Guinea": "Papua-Nova Guiné",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Philippines: "Filipinas",
  Poland: "Polônia",
  Portugal: "Portugal",
  Qatar: "Catar",
  Romania: "Romênia",
  Russia: "Rússia",
  "Saudi Arabia": "Arábia Saudita",
  Senegal: "Senegal",
  Serbia: "Sérvia",
  Singapore: "Singapura",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  Somalia: "Somália",
  "South Africa": "África do Sul",
  "South Korea": "Coreia do Sul",
  Spain: "Espanha",
  "Sri Lanka": "Sri Lanka",
  Sudan: "Sudão",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Syria: "Síria",
  Taiwan: "Taiwan",
  Tanzania: "Tanzânia",
  Thailand: "Tailândia",
  Tunisia: "Tunísia",
  Turkey: "Turquia",
  Uganda: "Uganda",
  Ukraine: "Ucrânia",
  "United Arab Emirates": "Emirados Árabes Unidos",
  "United Kingdom": "Reino Unido",
  "United States of America": "Estados Unidos",
  Uruguay: "Uruguai",
  Uzbekistan: "Uzbequistão",
  Venezuela: "Venezuela",
  Vietnam: "Vietnã",
  Yemen: "Iêmen",
  Zambia: "Zâmbia",
  Zimbabwe: "Zimbábue",
};

export { countryNamesPt };
